server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/njila-payement-db
spring.datasource.username=postgres
spring.datasource.password=Albane64
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibrnate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis properties
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000ms
#Idempotency Keys TTL
idempotency.ttl=86400

#RabbitMq properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=health,info


#CamPay properties
campay.base.url=https://demo.campay.net/api
campay.username=FWkpbiL340xkZ9k0PcSNN1sSX7O2iCx4RxS-WrQ8Pl-zrSSriuD59LtlbTnJy4eVh-uFkdrc1u6Eg-02gcF8pA
campay.password=DDTE0rm1Q_1dxpba--S5cBnMMCgr9Sxi69wmd7Z8op6seLuVSRyWP6isHMp56IsEJ_K0jVxsxOEXka4keqfgLg
