# njila-notification-service.properties
server.port=8085

redis.host=localhost
redis.port=6379
rabbitmq.host=localhost
rabbitmq.port=5672

PUBLIC_VAPID_KEY=BLTr8kheUW0CNymfubecI6Kba0Fu5NE45cPEnF9FHYSqzsqqSR0uNvc_inXrNL8iJsva3BIm1XCPxDQR8D8A37U
PRIVATE_VAPID_KEY=GhyYpewzORgPlgYVe6Nvh79hBO_HvxxsGWfk1etMBmM

# GMAIL SMTP
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=terrabia237@gmail.com
SMTP_PASS=wxqt fuqa kgub jzih 

DB_NAME=njila-notification-db
DB_USER=njila
DB_PASSWORD=njila2026
DB_HOST=localhost
DB_PORT=5432