# ─── Serveur ──────────────────────────────────────────────────────────────────
server.port=8083

# ─── Base de données PostgreSQL ───────────────────────────────────────────────
# Convention NJILA : njila-{domaine}-db
spring.datasource.url=jdbc:postgresql://localhost:5432/njila-booking-db
spring.datasource.username=njila
spring.datasource.password=njila2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── Redis — Verrou anti-doublon ──────────────────────────────────────────────
# Clé : njila:booking:lock:{idVoyage}:{idVoyageur}  TTL 10 min
spring.redis.host=localhost
spring.redis.port=6379

# ─── RabbitMQ ─────────────────────────────────────────────────────────────────
# Exchange : njila.booking.exchange  (convention njila.{domaine}.exchange)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ─── Eureka ───────────────────────────────────────────────────────────────────
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ─── Actuator ─────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info

# ─── URLs services internes ───────────────────────────────────────────────────
# Appels REST vers fleet-service et user-service
njila.fleet-service.url=http://localhost:8088
njila.user-service.url=http://localhost:8082

# ─── Numéro unique billet ─────────────────────────────────────────────────────
# Format : {CODE_AGENCE}-{TYPE}-{YYYYMMDD}-{CODE_FILIALE}-{SEQUENCE}
# Exemple : GEN-WEB-20260321-BYDE-000142
njila.booking.ticket.sequence-padding=6

# Dossier de stockage des billets PDF
njila.booking.billets.repertoire=/tmp/njila/billets



# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha