# ── Serveur ( — Microservices et ports) ─────────────────────────────────────
server.port=8081

# ── Base de données (§3 — njila-auth-db | PostgreSQL 15) ─────────────────────
db.name=njila-auth-db
db.user=njila
db.password=njila2026
db.host=localhost
db.port=5432

# ───────────────Secret key───────────────────
SECRET_KEY=njila-secret-key-2026-change-in-production

# ── Redis (§4 — AWS ElastiCache | port 6379) ──────────────────────────────────
redis.host=localhost
redis.port=6379

# ── RabbitMQ (§5 — AWS MQ Broker | port 5672) ────────────────────────────────
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.user=guest
rabbitmq.pass=guest
rabbitmq.vhost=/

# ── JWT ───────────────────────────────────────────────────────────────────────
jwt.access.minutes=15
jwt.refresh.days=7
